### ISSUE TITLE
ECS: Static Data Directory is Hard Coded

### ISSUE THREAD

**Issue by firefly2442** [Pulsar4xDevs/Pulsar4x#110]
In the `ECS-CrossPlatform` branch, in `StaticDataManager.cs` the default data directory location is hardcoded.  This results in the requirement to copy the `Data` folder out to the root folder in order for the unit tests to work (among other things I would imagine).  There are TODO notes in the file about making this folder location configurable.

Perhaps we could have a JSON file or some sort of configuration in the root directory that points to the folder and that would allow easy swapping between ECS, non-ECS libraries, etc.?

**Comment by se5a** [comment]
Really needs to be selectable from the game start/creation gui.
This is one of those problems that could be harder than it looks, currently I think the gui needs the json files to actually get that far anyway. then there's also things like if we want a mod that just changes a couple of the existing default/stock parts - you'd want to load the stock json, then load the mod ontop, replacing any GUID conflicts with the newer. rather than bloating small mods and requiring them to have all the json data. (this may happen already? it was the intent, but not sure if implemented).

This is also somewhat related to: https://github.com/Pulsar4xDevs/Pulsar4x/issues/81
The savegame should reference it's data directory(s) so in the case of loading a previously started game, you just need to load the save.

**Comment by firefly2442** [comment]
It's also needed for the unit tests which I think should be a priority to get working "out of the box".

**Comment by se5a** [comment]
yeah... I'd prefer the unit tests not to need it but not sure how much work that'd be.

**Comment by se5a** [comment]
Ok so I wrote a test to check if a mod loaded after the default data is loaded will overwrite default data if the guid is the same. it does. 

I'm thinking the default data directory should remain hardcoded.
mods should then be loaded ontop of the default data.
need to think of a way for mods to indicate they should completely flush the existing default data if required though. maybe a line in the versioninfo?

**Comment by se5a** [comment]
Do you want to tackle this @firefly2442 ? 
I'd have viewmodels.NewGameOptionsVM look through subdirectories in the Data directory for VersionInfo.vinfo files and have a public property list of them,
then in the CrossPlatformUI.NewGame.jeto have maybe a list of checkboxes for each of the list items.
if you're familiar with wpf MVVM you shouldn't have too much trouble figuring it out. I'm not sure that eto has a checkbox list built in, you may have to create something suitable, check the https://github.com/picoe/Eto/wiki for info, the Gimpnet ##eto.forms IRC chan is also helpfull if you get stuck. 

A checkbox list would allow un-selection of the default data and allow a game to be started with a number of different mods, might need to allow some sort of priority for which gets loaded first in the event of multiple being selected at once, but for now just get a list where multiple items can be selected in.

**Comment by firefly2442** [comment]
Sure, I'll give it a try.

**Comment by firefly2442** [comment]
I'm stuck on the following error message when I open up .jeto files.  I believe I'm getting this under Linux and Windows.  There seems to be some sort of conflict between the updated version of Newtonsoft and the Eto JSON library?  I can't find any mention or use of Newtonsoft 7.0.0.0 anywhere.

I've tried/read the following:
https://github.com/picoe/Eto/wiki/Troubleshooting-%26-Common-Problems#problem-newtonsoftjson-is-clearly-available-etojson-refuses-to-load-it
https://stackoverflow.com/questions/21498074/how-can-i-fix-assembly-version-conflicts-with-json-net-after-updating-nuget-pack
https://stackoverflow.com/questions/17776090/newtonsoft-json-assembly-conflict

![newtonsoft-error](https://cloud.githubusercontent.com/assets/531175/12741955/d9197474-c946-11e5-9f3b-2cd4cab29ba2.png)

**Comment by se5a** [comment]
Have you done this: https://github.com/picoe/Eto/wiki/Quick-Start

**Comment by se5a** [comment]
if you have and you're still getting problems, try roll back that Json library. I found that the Portable.Xaml library had to be rolled back to 0.6.1... might be a similar issue, though maybe only one that shows up in mono.

**Comment by Rod-Serling** [comment]
See commit 8d405f01301cbf627fcc2bccb981ac063b00e3c9 That fixed all unit tests for me, as well as told the compiler to automatically move the default data to the output directory. All unit tests and AppVeyor are now passing.

I don't believe there's a real need for swapping data directories. The data directory is hardcoded properly, like most games, and the StaticDataStore is capable of loading different mods from different sub-directories of the Data folder (with "Pulsar4x" being the default, hardcoded "mod").

Feel free to disagree with me, but since this issue rests mostly with getting AppVeyor to build (with all unit tests), I'm going to close it. If having the data directory not hardcoded is still an issue for other reasons, we can open another issue to discuss it.
