### ISSUE TITLE
ECS-Lib project separation. 

### ISSUE THREAD

**Issue by se5a** [Pulsar4xDevs/Pulsar4x#134]
This is future stuff, after we've got something playable and out the door.

So the licensing thing got me thinking that the ECSLib could be a standalone game engine and how it might best be split. 

Snopy pointed me at this which looks good: https://github.com/blog/2104-working-with-submodules
basicaly we have a couple of repositorys under the pulsar4xDevs here: https://github.com/Pulsar4xDevs

I'm thinking something along the lines of the Pulsar4X repository which contains gamedata, and pulls from:
ECSLibCoreRepo
ECSLibBlobsAndProcessorsRepo? <- should we split this from the core ? 
ECSLibUIRepo

Itd make the licencing easier, and we could have a different person as lead dev for each repo as well. 

Thoughts? 
better ideas on how to split it? 

The biggest issue is making it easy for new devs to figure out how to get the entire pulsar4x project, and keep the submodules/repos updated.

**Comment by SnopyDogy** [comment]
I'm not sure about Submodules, the seem to have some problems. I'd want some hands on experience first.

also a possible alternative:
http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by firefly2442** [comment]
I've used git submodules before and it was pretty straightforward.  I never ran into any of the issues the [author mentions as problems](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/).  I think some of the problems could be resolved by improved training and making sure all submodules live in their own folder (which is how most projects do it).  This makes sure people don't go in there and change files manually.

However, in our case since all of this stuff is (probably) tightly coupled, maybe git subtrees would be the best way?  I've never used them.

**Comment by DifferentLevelDan** [comment]
I've actually done some thought/work on this in the past few weeks aswell. If we were to split, we would pull basically the ECS architecture out of ECSLib, and put it in the (new) Engine lib.

The Engine would hold EntityManager, Entity, ProtoEntity, ProcessorBase, BaseDataBlob, StarSystem, (Which would be renamed to a more generic "GameWord"), Serialization, StaticData and run the GameLoop. In the future it may handle Input, Sound, and even Graphics. This is similar to a modern game engine.

The rest of the ECSLib, with the specific DataBlob types, and specific Processors would be the "Game" library, which contains the data from the game itself. They would derive from the base types provided by the engine and implement their own functionality on top of it. I've started to do this with Processors in the ECS-Processor branch. The OrbitProcessor could derive from the abstract TimedSystemProcessor (Which would be provided by the Engine) to run its code.

Licensing in this instance would put the Engine as LGPL or even MIT, since it contains 0 game code, the Game library, ViewModels, and View would be more GPL.

As for using Submodules or subtrees, i have no experience on either and don't feel comfortable commenting on their usage.

**Comment by SnopyDogy** [comment]
I really don't like the idea of us creating our own game engine. For one reason it would mean the "bottom" level of our game's architecture would contain platform specific code (all the audio and 3d stuff). at the moment the only thing our engine needs is an implementation of .net. going the full game engine route would change that. If we want to go the route lets pick an existing game engine and use that.

Second is that I like the idea of having a game library which contains the game simulation and the minimum possible infrastructure to run that simulation. You don't need input (other then disk access which .net gives us) or 3d Graphics or Audio for the simulation to run. You do need these thing in the interface. By creating a self supporting headless game library we can make it easy to extend the game with other interfaces, e.g. you can host the engine in its own thread behind a WPF UI, or you could host it as a service on a server and interact with it via a network client or web page. If you make the game rely on a full game engine you make it a lot harder to do this. you also end up support 3d graphics feature that work in a native client but would be  dead code for a web client.

I would split the project into three repos:
1) The first would be the game/simulation library, this would contain all the game rules/logic and the minimum possible infrastructure to support it. this would be license under LGPL.
2) Second would be a repo for the official game data, licensed under GPL or perhaps some version of the creative commons license.
3) An official front end UI. this would contain all the logic related to interacting with the simulation, modding tools, 3d graphics and audio support. licensed under GPL.

**Comment by se5a** [comment]
Yeah maybe game engine is wrong...  Maybe call it a Game database and logic
engine.  
I'm on the same page with the audio etc.  Keep the core thin.  Like
how ogre3d is a graphics engine,  but doesn't do io or audio or physics etc.

**Comment by se5a** [comment]
@firefly2442 it's not so tightly coupled as you might think. the blobs shouldn't need to reference much other stuff in the ecs except for a couple of special types.
the ECS doesn't reference the viewmodels at all, and the viewmodels don't reference the views/ui (except for some openTK stuff which I started to weed out) 
You going to come back and help out? hell, just some sketched ideas of what some views could look like would be useful.
