### ISSUE TITLE
ECS: Game Engine time advancement

### ISSUE THREAD

**Issue by DifferentLevelDan** [Pulsar4xDevs/Pulsar4x#135]
Currently the engine does not have a sufficent way to advance time. We've agreed upon creating a game loop. The game loop needs to have a time multiplier and a control that can scale back the time multiplier if the GameUpdates are taking too long.

A basic RunEngine() function has been added to the Game class on the ECS-Processors branch to handle this. RunEngine is not currently capable of scaling back the TimeMultiplier if FixedUpdates are taking too long, and is not hooked up to processor advancement.

This is required for ECS - Release 1: Constructions Cycle

**Comment by DifferentLevelDan** [comment]
This issue could be pushed to future releases, but the longer we wait, the worse off we are in my opinion. Would like to hear discussion regarding the timing on implementing this.

**Comment by SnopyDogy** [comment]
we should get it working for release 1.

What defines "too long". I don't believe the game needs to be 100% real time, which would imply that > 33ms would be too long. I think we could set a limit of 500ms - 1000ms or something like that, and only if it starts taking longer then that should it reduce the time multiplier. We also need to consider that the game may want to reduce the time multiplier for things like combat.

Oh and we need to consider how this appears to the player. I suspect that simply multiplying the size of the time step in a game loop/sudo real time situation would seem weird to the player, given that each frame of the game would be different length. i.e. with the same multiplier going at 100ms a frame then after 1 second it would look like X time had past. When the game is running at 200ms a frame then only X/2 time will seemed to have passed. In a real time game you would use the length of the previous frame to adjust the amount of work/progress in this frame, aka delta time. But if we a discrete time step for the frame that won't really work.

I suppose we would need to link it so the player can assume that when they set a time multiplier it is multiplying real time. e.g. a multiplier of 60 would be 1 minute per second. then engine would then try to deliver that in say 1 second sub-steps, if it can't for whatever reason then it would turn down the multiplier or turn up the sub-step (might not be possible), i.e. if it was taking 33ms per frame instead of 16ms then it would know after a few sub-steps that it will not get to the 60 seconds at then end of the second and would instead adjust the multiplier to 30 which is its current effective rate. The player would see this and know that the game is running slower. To prevent the game from always slowing down the preference should always be to increase sub-step time, but this may not be possible if, for example, combat was on going.

I hope the above made sense.

**Comment by se5a** [comment]
This is kind of a big thing, if it's slowing stuff down then we should move it to release 2.

**Comment by se5a** [comment]
This is done, enough to be closed. see https://github.com/Pulsar4xDevs/Pulsar4x/wiki/GameLoop-and-Interupts.
