### ISSUE TITLE
Strange issue with making ships orbit along with the body they are on

### ISSUE THREAD

**Issue by tsonnier** [Pulsar4xDevs/Pulsar4x#165]
Either adding the OrbitDB from the planet a ship is on or copying it results in strange behavior where one or the other will orbit, but not both entities.

**Comment by se5a** [comment]
The orbit processor works a little differently to how I initially expected. 
It finds the parent star, gets that parent stars orbitDB, then recurses through each of it's child DBs.

OrbitDB inherits from TreeHierachyDB, which is poorly documented, I'm trying to get an idea of how it works and what happens when it's copied. 

at first glance, I can't see why either adding a reference to a planets orbitDB or a clone of the planets orbitDB would cause this behavior. I'll have to look closer and actualy run it I think.

**Comment by se5a** [comment]
yeah I'm stumped.  
This works as expected:
`Entity ship = ShipFactory.CreateShip(shipClass, sol.SystemManager, factionEntity, position, sol, "Serial Peacemaker");
ship.SetDataBlob(earth.GetDataBlob<PositionDB>()); //first ship reference PositionDB`

This causes Earth to remain in position while the ship orbits the sun:
`Entity ship2 = ShipFactory.CreateShip(shipClass, sol.SystemManager, factionEntity, position, sol, "Ensuing Calm");
 ship2.SetDataBlob(earth.GetDataBlob<OrbitDB>());//second ship reference earth OrbitDB`

This has the ship sitting in place while everything else orbits. 
`Entity ship3 = ShipFactory.CreateShip(shipClass, sol.SystemManager, factionEntity, position, sol, "Contiual Pacifier");
ship3.SetDataBlob((OrbitDB)earth.GetDataBlob<OrbitDB>().Clone());//second ship clone earth OrbitDB`

**Comment by se5a** [comment]
The behaviour when referencing the orbitDB makes sense since the inherited TreeHierachyDB can only have a single parent entity. (ie the entity that the orbitDB belongs to)

When cloning the orbitDB we need to call the orbitDB.SetParent(newEntity)

Edit: no that's not right. the ParentEntity is the next node up the tree.
it's the OwningEntity. which still holds true for referencing the orbitDB. 
cloning I'm still unsure about, since SetDataBlob should set the blobs OwningEntity.

**Comment by DifferentLevelDan** [comment]
OrbitDB didn't really have a good way to create a new child with.

The usage has been simplified to create a "stationary" orbit for ships. Simply use ``new OrbitDB(parentEntity);`` and an OrbitDB will be created with the correct parent and stationary data.
