### ISSUE TITLE
Opening component design view throws TargetInvocationException

### ISSUE THREAD

**Issue by ghosta0815** [Pulsar4xDevs/Pulsar4x#188]
Steps to reproduce:
1. Build game
2. Create new Game (File > New Game)
3. Us default settings
4. Click Commponent Design View

Exception Text:

> System.Reflection.TargetInvocationException was unhandled
> Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll

**Comment by se5a** [comment]
Odd... I'm not getting that at all. 
double check what branch you're on (I'm presuming its the ECS-CrossPlatform branch)
check which startup project you're running (I'm presuming it's the WPF one, rather than GTK2) 
what line in which class does it break on? (I presume you're running in debug from VS) 
There may be an inner exception. see if you can find that too. 

also give it a try on the eto.dev branch, both in WPF and in GTK2 if you can figure out how to get that running (I think I put some instructions somewhere... the Linux Support Issue probably, you'll need to add the location for nuget to get the latest dev builds of eto) if you can't figure that one out, don't worry too much.

**Comment by ghosta0815** [comment]
Yes I am on the ECS-Cross Platform branch. and My Startup Project is WPF.

The exception is thrown in:
\Pulsar4X.CrossPlatformUI\Views\MainWindow.xeto.cs
line 51: view_tabs.Pages.Add(tp);

TabPage tp = new TabPage();
tp.Content = c;
tp.Text = title;
view_tabs.Pages.Add(tp);
if (activate) { view_tabs.SelectedPage = tp; }`

The inner exception looks like this:
[System.Reflection.TargetInvocationException.txt](https://github.com/Pulsar4xDevs/Pulsar4x/files/673146/System.Reflection.TargetInvocationException.txt)

**Comment by se5a** [comment]
I think that may be something that is fixed in the newer eto.forms lib. 
Try the etoDev branch, it's got the newer eto version in there and see if it still crashes. 

you'll have to add the package source for it, I've put instructions for doing that in monodevelop in the last post on this issue: https://github.com/Pulsar4xDevs/Pulsar4x/issues/3

the steps for visual studio will be a little bit different, but you should be able to figure it out.

**Comment by se5a** [comment]
humn, this didn't get closed. nice find on this, I don't think I'd have figured it out.
