### ISSUE TITLE
Recalculation of properties of entities happens in arbitrary order

### ISSUE THREAD

**Issue by AbuDhabi** [Pulsar4xDevs/Pulsar4x#212]
This is the probable reason why TestShipCreation() in ECS-Experimental fails - ReCalculateShipTonnaageAndHTK happens AFTER CalcMaxSpeed when the entity is recalculated.

The ReCalcAbilities() has a foreach loop that appears to not care about order of the operations. Either that, or it is implicitly in the wrong order. Not sure how to fix either scenario.

**Comment by se5a** [comment]
Yeah that might be a problem,
It'll be doing it in the order of the datablob types in Entity.Datablobs which is not going to be in the order we want at all.

The ReCalcAbilities is something I want to try and do differently anyway since it requires editing that file every time a new ability feature is added, and I want to move away from that. 
Coming up with a better way to do this is already one of the cards in one of the github projects "https://github.com/Pulsar4xDevs/Pulsar4x/projects/2#card-3180130"

I don't want to be going through every component a ship has every tick either, that's going to be something like an  O(n1*n2) operation for each entity. n1 being the number of datablobs and n2 being the number of component attributes. 
I can see that ballooning up real quick as we start to add more features, having it only do it when something requires an entity to recalculate all it's abilities is fairly important.

**Comment by AbuDhabi** [comment]
OK, one way I can see how this can be solved and potentially optimized a little is:
- Put a set of flags of some sort on components, to mean which portions of the parent entity they (potentially) affect and therefore need to be recalculated.
- Modify ReCalcProcessor to work on top-level entities (ships, colonies, etc), rather than their components.
- The delegate actions would then be something like ShipProcessor.RecalculateShip(parent, component), called by ReCalcProcessor.ReCalcAbilities(parent, component).
- Internally, RecalculateShip() would call any prerequisite subcalculations, in a proper order. 

So, suppose you add engines to a ship. 
1. After adding the component, ReCalcAbilities gets called with the ship and the component.
2. ReCalcAbilities figures out that the parent is a ship, and calls RecalculateShip(), passing it the arguments it got.
3. RecalculateShip() checks the flags on the component and finds that it needs to run two subroutines, first to recalculate the tonnage and hits to kill, second to recalculate maximum speed. 
4. RecalculateShip calls the required methods in predetermined sequence, which modify the calculated values like tonnage and maximum speed.

Any particular problems with this approach?

**Comment by AbuDhabi** [comment]
OK, never mind that. I don't understand the local architecture yet.

Different solution: Merge Tonnage/HTK and MaxSpeed, since everything that modifies tonnage, also likely affects speed. And I would guess that most things that affect speed also affect tonnage in practice, too.

**Comment by se5a** [comment]
The ReCalcProcessor is already working on top-level entities currently.
What we should probably do is change the component designs from an entity with a bunch of attribute datablobs into some other Type.
This will mean that we can use functions in the attributes since they won't be datablobs anymore. 
I don't think there's a compelling reason for designs to be an entity,
designs don't get processed on a regular basis.

**Comment by se5a** [comment]
if you uncomment the call to Recalc the speed in the Tonnage and HTK function, does that fix the problem? 
If so we could do that as a short term solution, and leave this open till we figure a way to fix it properly.

**Comment by AbuDhabi** [comment]
I'll investigate as soon as I have some free time! Probably later this week.

**Comment by AbuDhabi** [comment]
Made a pull request here: https://github.com/Pulsar4xDevs/Pulsar4x/pull/213
