### ISSUE TITLE
Could not open project on Windows csproj files incorrect.

### ISSUE THREAD

**Issue by MADavies** [Pulsar4xDevs/Pulsar4x#228]
I pulled the latest version of master to see how you guys were doing with this. I couldnt open the project in VisualStudio 2013 Ultimate due to incorrect .csproj in ESCLib, ImGuiNetUI and Tests. Reverting to using the old csproj files appears to allow Visual studio to load the projects.

**Comment by se5a** [comment]
You will need a newer version of VS than that, a lot has changed in the language in six years, and MS prefers to push completely new versions of the IDE to handle that, rather than patch existing versions. VS 2013 wont even compile C#6 without a lot of massaging, I'm not even 100% sure the readme is correct that 2015 is enough to handle the new csproj type
If I switch to using .net core (something I've been tempted to do for a long while) then you'd need at least VS2017 I think. 

your options are:
 - VS community edition(free)
 - VSCode, 
 - Rider, 
 - MonoDevelop.

**Comment by se5a** [comment]
Note: you can have multiple versions of VS installed on the same machine. (or at least, you used to be able to do this without a problem)
