### ISSUE TITLE
Component designer causes crashes

### ISSUE THREAD

**Issue by agm-114** [Pulsar4xDevs/Pulsar4x#249]
Selecting a Beam Fire Control or Test weight in the component designer causes a crash.
I was unable to get any debugger info

Program freezes for a bit, then hard exits with no error messages

![Test](https://user-images.githubusercontent.com/46271745/73115639-df73b300-3ef6-11ea-9b6a-6c9bd2f21a73.gif)

**Comment by se5a** [comment]
I'm pretty sure this is due to Imgui.Text(string) not liking a null value...
should be an easy fix once I figure out why ComponentDesignAttribute.Description is getting set to null.

**Comment by se5a** [comment]
should be fixed in this commit: https://github.com/Pulsar4xDevs/Pulsar4x/commit/bcaccac7aad296769b70647a0145eb70722eefd7 
(latest dev branch). 
Confirm and close if you can.   

Note this is something that will very possibly occur in the future in other places. in windows/VS it appears to crash without an error (does the console show anything?) 
In Linux you'll likely get a funky looking string with lots of ????????? in it. 
It's a limitation of the current version of imgui.net
https://github.com/mellinoe/ImGui.NET/issues/120

**Comment by se5a** [comment]
Yeah I can't replicate this in the dev branch in a virtual box (win10 and VS) since that commit. agm still reports it happening though?
