### ISSUE TITLE
Detection wavelength causes crash

### ISSUE THREAD

**Issue by agm-114** [Pulsar4xDevs/Pulsar4x#251]
Maxing Detection Wavelength on a passive sensor in the part designer causes a crash

![image](https://user-images.githubusercontent.com/46271745/73115686-7ccee700-3ef7-11ea-828b-c9c8636d1079.png)

**Comment by se5a** [comment]
The crash should be fixed, but there's still something a bit funky going on here. 
Now currently it has a problem where despite the max value being 1e12, setting the slider all the way to the max in the ui gets a result of something like ~ 9999999995904.0000

The underlying issue I think, is that the value is getting turned into a string in `ComponentDesignAttribute.SetValueFromInput()` here: https://github.com/Pulsar4xDevs/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ECSLib/ComponentFeatureSets/Components/ComponentDesignAttribute.cs#L62

Should probably look to see if we can store it as a numerical value instead of a string value when it can be changed via user input rather than getting the value from the formula field.
