### ISSUE TITLE
Version# Watermark

### ISSUE THREAD

**Issue by agm-114** [Pulsar4xDevs/Pulsar4x#252]
Having a version numbered visible at times in the bottom corner of the game screen would make it clear from which version of the game screenshots come from

**Comment by se5a** [comment]
Yup agreed, any ideas on how we should accomplish this?  I'm thinking maybe grabbing the git commit ID somehow.

**Comment by se5a** [comment]
https://stackoverflow.com/questions/15141338/embed-git-commit-hash-in-a-net-dll has some ideas on how we might achieve this. maybe taking the commit on the end of the version would be the best way to do it, since it's not unlikely that contributors will be working off local repos with a few unpushed commits.

**Comment by se5a** [comment]
done in this commit:  https://github.com/Pulsar4xDevs/Pulsar4x/commit/2fc638c0f41af11fc20c7ddddd59b18a9d096a59
