### ISSUE TITLE
ImGui.GetContentRegionAvail() returns 0,0 ;

### ISSUE THREAD

**Issue by agm-114** [Pulsar4xDevs/Pulsar4x#270]

**Comment by se5a** [comment]
Just to add some info:
This is happening on one (that we know of) PC running windows 10.
symptoms are the UI layout not looking right. 
a breakpoint was put at https://github.com/Pulsar4xDevs/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ImGuiNetUI/EmpireManagement/ComponentDesignUI.cs#L53 
and was found that GetContentRegionAvail() was returning 0,0. 

As of yet we have no idea why this one PC is doing this but none others. 
opening the IMGUI demo window within the game looks correct (which uses this in some places)
however the demo window will be using the native cpp calls instead of going through the .net wrapper. 

Suggest we create a minimal program with just imgui.net and a window that uses GetContentRegionAvail and see if this minimum environment still gives the same result. 
if it does we can try push it up the chain to imgui.net and seek help from them for more suggestions.

**Comment by agm-114** [comment]
Window added in 8fda37f8a2545248c24c45c63f98e085db69ea5a with the following results from munashe:
![image](https://user-images.githubusercontent.com/46271745/76240100-079a4580-6209-11ea-97f0-ab79b9c38d71.png)

**Comment by behindcurtain3** [comment]
I think the UI has changed enough that whatever was causing this no longer exists.
